version: "3.8"

services:
  wireguard-gw:
    image: linuxserver/wireguard
    container_name: wireguard-gw
    volumes:
    - '/etc/private-lan/volumes/wireguard-gw/:/config'
    networks:
      net:
        ipv4_address: 172.16.238.2
    restart: unless-stopped
    privileged: true
    cap_add:
    - NET_ADMIN
    - SYS_MODULE

  wireguard-dns:
    image: linuxserver/wireguard
    container_name: wireguard-dns
    volumes:
    - '/etc/private-lan/volumes/wireguard-dns/:/config'
    networks:
      net:
        ipv4_address: 172.16.238.8
    restart: unless-stopped
    privileged: true
    cap_add:
    - NET_ADMIN
    - SYS_MODULE

  dnsmasq:
    build: images/dnsmasq
    container_name: dnsmasq
    networks:
      net:
        ipv4_address: 172.16.238.3
    expose:
      - "67/udp"
      - "68/tcp"
    volumes:
      - '/etc/private-lan/volumes/dnsmasq/:/etc/dnsmasq.d/'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      depends_on:
        - dhcp-helper

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    networks:
      net:
        ipv4_address: 172.16.238.4
    ports:
      - "192.168.178.2:53:53/tcp"
      - "192.168.178.2:53:53/udp"
      - "192.168.178.2:80:80/tcp"
      - "192.168.178.2:443:443/tcp"
    environment:
      DNS1: '172.16.238.6'
      DNS2: 'no'
      DNSMASQ_LISTENING: 'all'
    volumes:
      - '/etc/private-lan/volumes/pihole/gravity/:/etc/pihole/gravity/'
      - '/etc/private-lan/volumes/pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf'
      - '/etc/private-lan/volumes/pihole/pihole/pihole/:/etc/pihole/'
      - '/etc/private-lan/volumes/pihole/pihole/dnsmasq/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    restart: unless-stopped
    depends_on:
      - unbound

  pihole-vpn:
    image: pihole/pihole:latest
    container_name: pihole-vpn
    networks:
      net:
        ipv4_address: 172.16.238.5
    ports:
      - "192.168.178.3:53:53/tcp"
      - "192.168.178.3:53:53/udp"
      - "192.168.178.3:80:80/tcp"
      - "192.168.178.3:443:443/tcp"
    environment:
      DNS1: '172.16.238.7'
      DNS2: 'no'
      DNSMASQ_LISTENING: 'all'
    volumes:
      - '/etc/private-lan/volumes/pihole/gravity/:/etc/pihole/gravity/'
      - '/etc/private-lan/volumes/pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf'
      - '/etc/private-lan/volumes/pihole/pihole-vpn/pihole/:/etc/pihole/'
      - '/etc/private-lan/volumes/pihole/pihole-vpn/dnsmasq/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    restart: unless-stopped
    depends_on:
      - wireguard-gw
      - unbound-vpn

  unbound:
    build: images/unbound
    container_name: unbound
    networks:
      net:
        ipv4_address: 172.16.238.6
    expose:
      - "53/udp"
      - "53/tcp"
    volumes:
      - '/etc/private-lan/volumes/unbound/unbound.conf:/etc/unbound/unbound.conf'
    restart: unless-stopped
    depends_on:
      - wireguard-dns

  unbound-vpn:
    build: images/unbound
    container_name: unbound-vpn
    networks:
      net:
        ipv4_address: 172.16.238.7
    expose:
      - "53/udp"
      - "53/tcp"
    volumes:
      - '/etc/private-lan/volumes/unbound/unbound.conf:/etc/unbound/unbound.conf'
    restart: unless-stopped
    depends_on:
      - wireguard-gw

  dhcp-helper:
    build: images/dhcp-helper
    container_name: dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.16.238.3
    cap_add:
      - NET_ADMIN

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1