version: "3.8"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    networks:
      net:
        ipv4_address: 172.16.238.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      DNS1: '172.16.238.4#5300'
      DNS2: 'no'
      # If you enabled DNSSEC in dnscrypt-proxy
      # DNSSEC: 'true'
      DNSMASQ_LISTENING: 'all'
    volumes:
      - '/etc/private-lan/volumes/etc-pihole/:/etc/pihole/'
      - '/etc/private-lan/volumes/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    restart: always
    depends_on:
      - dnscrypt-proxy
      - dhcp-helper

  dnscrypt-proxy:
    build: files/dnscrypt-proxy
    container_name: dnscrypt-proxy
    networks:
      net:
        ipv4_address: 172.16.238.4
    expose:
      - "5300/udp"
      - "5300/tcp"
    volumes:
      - '/etc/private-lan/volumes/dnscrypt-proxy/:/config/'
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - wireguard

  dhcp-helper:
    build: files/dhcp-helper
    container_name: dhcp-helper
    restart: always
    network_mode: "host"
    command: -s 172.16.238.3
    cap_add:
      - NET_ADMIN

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard-gateway
    volumes:
    - '/etc/private-lan/volumes/wireguard-gateway/:/config'
    networks:
      net:
        ipv4_address: 172.16.238.2
        ipv6_address: 2001:3984:3989::2
    restart: always
    privileged: true
    cap_add:
    - NET_ADMIN
    - SYS_MODULE

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1